chore(deps): bump zod-openapi from 4.2.4 to 5.4.3 (#1141)
Bumps [zod-openapi](https://github.com/samchungy/zod-openapi) from 4.2.4
to 5.4.3.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/samchungy/zod-openapi/releases">zod-openapi's
releases</a>.</em></p>
<blockquote>
<h2>zod-openapi@5.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/541">#541</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/fbdc3630e3d2517b9272dd991a5b777ea2480554"><code>fbdc363</code></a>
Thanks <a
href="https://github.com/apps/dependabot"><code>@​dependabot</code></a>!
- Resolve error TS2304: Cannot find name 'oas31_d_exports'.</li>
</ul>
<h2>zod-openapi@5.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/535">#535</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/1bdce137cbe52a2aec9b47606bd49fc977043096"><code>1bdce13</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! - Fix
component generation in OpenAPI 3.0.0</li>
</ul>
<h2>zod-openapi@5.4.1</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/520">#520</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/8d08bd6441998603c85e52c3d93eff04ce8f4664"><code>8d08bd6</code></a>
Thanks <a href="https://github.com/GeKorm"><code>@​GeKorm</code></a>! -
Fix <code>zod/mini</code> compatibility</li>
</ul>
<h2>zod-openapi@5.4.0</h2>
<h3>Minor Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/510">#510</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/dea9dbce89cd008e18a5bdec9c7e84903a8acd5e"><code>dea9dbc</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! -
Re-introduce support for OpenAPI 3.x. This requires Zod ^4.1.0</li>
</ul>
<h2>zod-openapi@5.3.1</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/4b8833024656ba04d7cf4fe1c36635c4345586f3"><code>4b88330</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! - Fix
manual component registration</li>
</ul>
<h2>zod-openapi@5.3.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a
href="https://github.com/samchungy/zod-openapi/commit/c43d5445e6bfaacbcbf5af6374ce783aba5c783c"><code>c43d544</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! -
Remove <code>zodSchemas</code> from meta <code>override</code></p>
<p>This should result in faster type inference when using
<code>.meta()</code>.</p>
<p><code>zodSchemas</code> is still available in the
<code>CreateDocumentOptions</code> <code>override</code> function.</p>
<p>The mis-scoped <code>Override</code> type is now exported as
<code>ZodOpenApiOverride</code> and
<code>ZodOpenApiOverrideMeta</code></p>
</li>
</ul>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/484">#484</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/8ae543fe95c3582553af4710a8ff7bf6540b0bca"><code>8ae543f</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! -
Switch to ESM</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/samchungy/zod-openapi/blob/master/CHANGELOG.md">zod-openapi's
changelog</a>.</em></p>
<blockquote>
<h2>5.4.3</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/541">#541</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/fbdc3630e3d2517b9272dd991a5b777ea2480554"><code>fbdc363</code></a>
Thanks <a
href="https://github.com/apps/dependabot"><code>@​dependabot</code></a>!
- Resolve error TS2304: Cannot find name 'oas31_d_exports'.</li>
</ul>
<h2>5.4.2</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/535">#535</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/1bdce137cbe52a2aec9b47606bd49fc977043096"><code>1bdce13</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! - Fix
component generation in OpenAPI 3.0.0</li>
</ul>
<h2>5.4.1</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/520">#520</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/8d08bd6441998603c85e52c3d93eff04ce8f4664"><code>8d08bd6</code></a>
Thanks <a href="https://github.com/GeKorm"><code>@​GeKorm</code></a>! -
Fix <code>zod/mini</code> compatibility</li>
</ul>
<h2>5.4.0</h2>
<h3>Minor Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/510">#510</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/dea9dbce89cd008e18a5bdec9c7e84903a8acd5e"><code>dea9dbc</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! -
Re-introduce support for OpenAPI 3.x</li>
</ul>
<h2>5.3.1</h2>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/4b8833024656ba04d7cf4fe1c36635c4345586f3"><code>4b88330</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! - Fix
manual component registration</li>
</ul>
<h2>5.3.0</h2>
<h3>Minor Changes</h3>
<ul>
<li>
<p><a
href="https://github.com/samchungy/zod-openapi/commit/c43d5445e6bfaacbcbf5af6374ce783aba5c783c"><code>c43d544</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! -
Remove <code>zodSchemas</code> from meta <code>override</code></p>
<p>This should result in faster type inference when using
<code>.meta()</code>.</p>
<p><code>zodSchemas</code> is still available in the
<code>CreateDocumentOptions</code> <code>override</code> function.</p>
<p>The mis-scoped <code>Override</code> type is now exported as
<code>ZodOpenApiOverride</code> and
<code>ZodOpenApiOverrideMeta</code></p>
</li>
</ul>
<h3>Patch Changes</h3>
<ul>
<li><a
href="https://redirect.github.com/samchungy/zod-openapi/pull/484">#484</a>
<a
href="https://github.com/samchungy/zod-openapi/commit/8ae543fe95c3582553af4710a8ff7bf6540b0bca"><code>8ae543f</code></a>
Thanks <a
href="https://github.com/samchungy"><code>@​samchungy</code></a>! -
Switch to ESM</li>
</ul>
<h2>5.2.0</h2>
<h3>Minor Changes</h3>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/a93d2ecbca417e5a481c3991214580039b4bbd21"><code>a93d2ec</code></a>
Version Packages (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/543">#543</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/fbdc3630e3d2517b9272dd991a5b777ea2480554"><code>fbdc363</code></a>
Bump tsdown from 0.14.2 to 0.15.6 (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/541">#541</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/732ccb6e6b3a5b9386caf4f6417a5360e06cd6f7"><code>732ccb6</code></a>
Version Packages (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/536">#536</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/dc64b6b2163f6e7a9f508e274a5062db71d14a01"><code>dc64b6b</code></a>
Bump zod from 4.1.5 to 4.1.11 (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/531">#531</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/1bdce137cbe52a2aec9b47606bd49fc977043096"><code>1bdce13</code></a>
Fix registering schemas in 3.0.0 (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/535">#535</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/50d81ba620d4d08bf4d4706ad4086b529f4e03a3"><code>50d81ba</code></a>
refactor: Redundant argument defaults in <code>createSchema</code> (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/533">#533</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/dd6c05e1288f0ee2d55994c4377e04bae4089ba8"><code>dd6c05e</code></a>
Version Packages (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/521">#521</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/9fb91fa8d00044e28e9472caa4e2679eb63ae148"><code>9fb91fa</code></a>
Bump <code>@​redocly/cli</code> from 2.0.7 to 2.0.8 (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/515">#515</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/f33e7c2d248d550b7161d84d9b62e0aab46d0652"><code>f33e7c2</code></a>
Bump tsdown from 0.14.1 to 0.14.2 (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/514">#514</a>)</li>
<li><a
href="https://github.com/samchungy/zod-openapi/commit/8d08bd6441998603c85e52c3d93eff04ce8f4664"><code>8d08bd6</code></a>
Fix <code>zod/mini</code> compatibility (<a
href="https://redirect.github.com/samchungy/zod-openapi/issues/520">#520</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/samchungy/zod-openapi/compare/v4.2.4...zod-openapi@5.4.3">compare
view</a></li>
</ul>
</details>
<details>
<summary>Maintainer changes</summary>
<p>This version was pushed to npm by [GitHub Actions](<a
href="https://www.npmjs.com/~GitHub">https://www.npmjs.com/~GitHub</a>
Actions), a new releaser for zod-openapi since your current version.</p>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=zod-openapi&package-manager=npm_and_yarn&previous-version=4.2.4&new-version=5.4.3)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>